### ISSUE TITLE
Fedora 38 Wayland: "gsettings set org.gnome.mutter.wayland xwayland-allow-byte-swapped-clients true" has no effect

### ISSUE THREAD

**Issue by PierreLinux** [ubuntu-flutter-community/ubuntu_flavor#11]
With Fedora 38, running GNOME with Wayland, the below command has no effect:

gsettings set org.gnome.mutter.wayland xwayland-allow-byte-swapped-clients true

I am not able to run any, say Oracle SPARC GUI, with Fedora 38 Wayland.

**Comment by jpnurmi** [comment]
Did you mean to report the bug somewhere else? This project is not related to GSettings - it's a simple Dart package for detecting Ubuntu flavors from the environment.

**Comment by PierreLinux** [comment]
Hello,


I meant to submit a case for that.

Regards,
PierreLinux

----- Reply message -----
From: "J-P Nurmi" ***@***.***>
To: "ubuntu-flutter-community/ubuntu_flavor" ***@***.***>
Cc: "Pierre Wakim" ***@***.***>, "Author" ***@***.***>
Subject: [ubuntu-flutter-community/ubuntu_flavor] Fedora 38 Wayland: "gsettings set org.gnome.mutter.wayland xwayland-allow-byte-swapped-clients true" has no effect (Issue #11)
Date: Fri, Jul 7, 2023 11:41 AM


Did you mean to report the bug somewhere else? This project is not related to GSettings - it's a simple Dart package for detecting Ubuntu flavors from the environment.
